add Add Dummy Dummy
sub Subtract Dummy Dummy
negateT Negate Dummy

m1 Point 5.5
m2 Point (-6.5)
m3 Point 1.5
ms Collection m1 m2 m3

n1 Point 4.5
n2 Point 5.4
n3 Point 1.2
ns Collection n1 n2 n3

negateNs Map1 negateT ns
negateMs Map1 negateT ms

sum1 Map2 add negateMs negateNs
sum2 Map2 add negateMs negateMs
sum3 Map2 add negateNs negateNs
sum4 Map2 add ms ns
sum5 Map2 add ns ns

sum6 Map2 add sum1 sum2
sum7 Map2 add sum6 sum3
sum8 Map2 add sum7 sum4
out Map2 add sum8 sum5

